foo:
  list:
    - name: my name
      description: my description
    - name: katherine
      description: a good girl
  hello: hello
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spittr?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: prod
---
spring:
  profiles: dev
foo:
  list:
    - name: my another name